# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60b03621d946aa11fbec03ff6ac8a0cb052d2c6b147e42e70394a8298b2fc5ec28ed983fefb2770188f2c4548d19ffb570ed6d2609391ad6b7d6ab700f6284ae

test:
  secret_key_base: 06861bab1709bbd9e35f90ecb9fcb4bcdcacc80c3f6fed265a69369fc1aeb5fe18c00b636763bf44d2e883f3ba380d2c5160397f0aacc29219f470dbdc358a14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
